In [21]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, fbeta_score
df=pd.read_csv(r"C:\Users\student\Downloads\train_cleaned_data.csv")


# Splitting the data into features (X) and target (y)
X = df.drop(columns=['Survived'])  # Dropping the target column
y = df['Survived']  # Target variable

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Defining the models
models = {
    'Linear Regression': LinearRegression(),
    'SVM': SVC(),
    'Naive Bayes': GaussianNB()
}

# Define the beta value for F-beta score
beta = 1  # You can change this value to whatever you prefer

# Training and evaluating the models
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    # For Linear Regression, we round the predictions to get binary values (0 or 1)
    if name == 'Linear Regression':
        y_pred = (y_pred > 0.5).astype(int)  # Threshold at 0.5
    
    # Evaluating accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print(f'{name} Accuracy: {accuracy:.4f}')
    
    # Generating and printing the confusion matrix
    cm = confusion_matrix(y_test, y_pred)
    print(f'{name} Confusion Matrix:')
    print(cm)
    
    # Calculating Precision, Recall, and F-beta Score
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    fbeta = fbeta_score(y_test, y_pred, beta=beta)
    
    print(f'{name} Precision: {precision:.4f}')
    print(f'{name} Recall: {recall:.4f}')
    print(f'{name} F-{beta} Score: {fbeta:.4f}')
    print()  # Blank line for better readability

Linear Regression Accuracy: 0.7877
Linear Regression Confusion Matrix:
[[89 16]
 [22 52]]
Linear Regression Precision: 0.7647
Linear Regression Recall: 0.7027
Linear Regression F-1 Score: 0.7324

SVM Accuracy: 0.5866
SVM Confusion Matrix:
[[105   0]
 [ 74   0]]
SVM Precision: 0.0000
SVM Recall: 0.0000
SVM F-1 Score: 0.0000

Naive Bayes Accuracy: 0.7709
Naive Bayes Confusion Matrix:
[[76 29]
 [12 62]]
Naive Bayes Precision: 0.6813
Naive Bayes Recall: 0.8378
Naive Bayes F-1 Score: 0.7515



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
