In [128]:
import numpy as np
def cosine__similarity(x, y):
    if len(x) != len(y):
        return None
    #dot product
    dot_product=np.dot(x,y)
    
    #compute l2 norm of x and y
    mag_x=np.sqrt(sum(x**2))
    mag_y=np.sqrt(sum(y**2))
    
    cosine_similarity=dot_product/(mag_x*mag_y)
    return cosine_similarity



corpus = [ 'data science is one of the most important fields of science',
 'this is one of the best data science courses',
 'data scientists analyze data' ]
    


In [129]:
from sklearn.feature_extraction.text import CountVectorizer

In [130]:
# Create a matrix to represent the corpus
X = CountVectorizer().fit_transform(corpus).toarray()

In [131]:
print(X)

[[0 0 0 1 1 1 1 1 2 1 2 0 1 0]
 [0 1 1 1 0 0 1 0 1 1 1 0 1 1]
 [1 0 0 2 0 0 0 0 0 0 0 1 0 0]]


In [132]:
cos_sim_1_2 = cosine__similarity(X[0, :], X[1, :])
cos_sim_1_3 = cosine__similarity(X[0, :], X[2, :])
cos_sim_2_3 = cosine__similarity(X[1, :], X[2, :])

In [133]:
print('Cosine Similarity between: ')
print('\tDocument 1 and Document 2: ', cos_sim_1_2)
print('\tDocument 1 and Document 3: ', cos_sim_1_3)
print('\tDocument 2 and Document 3: ', cos_sim_2_3)

Cosine Similarity between: 
	Document 1 and Document 2:  0.6885303726590962
	Document 1 and Document 3:  0.21081851067789195
	Document 2 and Document 3:  0.2721655269759087


# Lab TasK

In [173]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [199]:
twitter = """
Twitter is an online social media and social networking service owned
and operated by American company X Corp.,
the legal successor of Twitter, Inc. Twitter users outside the United
States are legally served by the Ireland-based
Twitter International Unlimited Company, which makes these users
subject to Irish and European Union data protection laws.
On Twitter users post texts, photos and videos known as 'tweets'.
Registered users can tweet, like, 'retweet' tweets,
and direct message (DM) other registered users, while unregistered
users only have the ability to view public tweets.
Users interact with Twitter through browser or mobile frontend
software, or programmatically via its APIs.
"""

In [200]:
facebook = """
Facebook is an online social media and social networking service owned
by American technology giant Meta Platforms.
Created in 2004 by Mark Zuckerberg with fellow Harvard College
students and roommates Eduardo Saverin, Andrew McCollum,
Dustin Moskovitz, and Chris Hughes, its name derives from the face
book directories often given to American university students.
Membership was initially limited to only Harvard students, gradually
expanding to other North American universities and,
since 2006, anyone over 13 years old. As of December 2022, Facebook
claimed 2.96 billion monthly active users, and ranked third
worldwide among the most visited websites. It was the most downloaded
mobile app of the 2010s. Facebook can be accessed from devices
with Internet connectivity, such as personal computers, tablets and
smartphones. After registering, users can create a profile
revealing information about themselves. They can post text, photos and
multimedia which are shared with any other users who have
agreed to be their friend' or, with different privacy settings,
publicly. Users can also communicate directly with each other with
Messenger, join common-interest groups, and receive notifications on
the activities of their Facebook friends and the pages they follow.
"""

In [201]:
tiktok = """
TikTok, and its Chinese counterpart Douyin (Chinese: 抖音; pinyin:
Dǒuyīn), is a short-form video hosting service owned by ByteDance.
It hosts user-submitted videos, which can range in duration from 3
seconds to 10 minutes. Since their launches, TikTok and Douyin have
gained global popularity.[6][7] In October 2020, TikTok surpassed 2
billion mobile downloads worldwide. Morning Consult named TikTok the
third-fastest growing brand of 2020, after Zoom and Peacock.
Cloudflare ranked TikTok the most popular website of 2021,
surpassing google.com.
"""


In [202]:
instagram = """
Instagram is a photo and video sharing social networking service owned
by American company Meta Platforms. The app allows users to upload media that can be edited with filters and organized by hashtags
and geographical tagging. Posts can be shared publicly or
with preapproved followers. Users can browse other users' content by
tag and location, view trending content, like photos, and follow
other users to add their content to a personal feed. Instagram was
originally distinguished by allowing content to be framed only in a
square (1:1) aspect ratio of 640 pixels to match the display width of
the iPhone at the time. In 2015, this restriction was eased with
an increase to 1080 pixels. It also added messaging features, the
ability to include multiple images or videos in a single post, and a
Stories feature—similar to its main competitor Snapchat—which allowed
users to post their content to a sequential feed, with each post
accessible to others for 24 hours. As of January 2019, Stories is used
by 500 million people daily.
"""

In [203]:
text=[twitter,facebook,tiktok,instagram]

In [204]:
numarray=np.array(text)

In [205]:
numarray

array(["\nTwitter is an online social media and social networking service owned\nand operated by American company X Corp.,\nthe legal successor of Twitter, Inc. Twitter users outside the United\nStates are legally served by the Ireland-based\nTwitter International Unlimited Company, which makes these users\nsubject to Irish and European Union data protection laws.\nOn Twitter users post texts, photos and videos known as 'tweets'.\nRegistered users can tweet, like, 'retweet' tweets,\nand direct message (DM) other registered users, while unregistered\nusers only have the ability to view public tweets.\nUsers interact with Twitter through browser or mobile frontend\nsoftware, or programmatically via its APIs.\n",
       "\nFacebook is an online social media and social networking service owned\nby American technology giant Meta Platforms.\nCreated in 2004 by Mark Zuckerberg with fellow Harvard College\nstudents and roommates Eduardo Saverin, Andrew McCollum,\nDustin Moskovitz, and Chris Hu

In [206]:
print(text[0])


Twitter is an online social media and social networking service owned
and operated by American company X Corp.,
the legal successor of Twitter, Inc. Twitter users outside the United
States are legally served by the Ireland-based
Twitter International Unlimited Company, which makes these users
subject to Irish and European Union data protection laws.
On Twitter users post texts, photos and videos known as 'tweets'.
Registered users can tweet, like, 'retweet' tweets,
and direct message (DM) other registered users, while unregistered
users only have the ability to view public tweets.
Users interact with Twitter through browser or mobile frontend
software, or programmatically via its APIs.



In [231]:
X1 = CountVectorizer().fit_transform(numarray)

In [212]:
cos_sim_1_2 = cosine_similarity(X1[0], X1[1])
cos_sim_1_3 = cosine_similarity(X1[0], X1[2])
cos_sim_1_4 = cosine_similarity(X1[0], X1[3])

print('Cosine Similarity between: ')
print('\n')
print('Document 1 and Document 2: ', cos_sim_1_2)
print('Document 1 and Document 3: ', cos_sim_1_3)
print('Document 1 and Document 4: ', cos_sim_1_4)





Cosine Similarity between: 


Document 1 and Document 2:  [[0.49812778]]
Document 1 and Document 3:  [[0.23269571]]
Document 1 and Document 4:  [[0.49395987]]


In [221]:
cos_sim_2_1 = cosine_similarity(X1[1], X1[0])
cos_sim_2_3 = cosine_similarity(X1[1], X1[2])
cos_sim_1_4 = cosine_similarity(X1[1], X1[3])

In [227]:
print('Cosine Similarity between: ')
print('\n')
print('Document 2 and Document 2: ', cos_sim_2_1)
print('Document 2 and Document 3: ', cos_sim_2_3)
print('Document 2 and Document 4: ', cos_sim_1_4)




Cosine Similarity between: 


Document 2 and Document 2:  [[0.49812778]]
Document 2 and Document 3:  [[0.34922161]]
Document 2 and Document 4:  [[0.60352796]]


In [225]:
cos_sim_3_1 = cosine_similarity(X1[2], X1[0])
cos_sim_3_2 = cosine_similarity(X1[2], X1[1])
cos_sim_3_4 = cosine_similarity(X1[2], X1[3])

In [226]:
print('Cosine Similarity between: ')
print('\n')
print('Document 3 and Document 1: ', cos_sim_3_1)
print('Document 3 and Document 2: ', cos_sim_3_2)
print('Document 3 and Document 4: ', cos_sim_3_4)

Cosine Similarity between: 


Document 3 and Document 1:  [[0.23269571]]
Document 3 and Document 2:  [[0.34922161]]
Document 3 and Document 4:  [[0.3047918]]


In [228]:
cos_sim_4_1 = cosine_similarity(X1[3], X1[0])
cos_sim_4_2 = cosine_similarity(X1[3], X1[1])
cos_sim_4_3 = cosine_similarity(X1[3], X1[2])

In [229]:
print('Cosine Similarity between: ')
print('\n')
print('Document 4 and Document 1: ', cos_sim_4_1)
print('Document 4 and Document 2: ', cos_sim_4_2)
print('Document 4 and Document 3: ', cos_sim_4_3)

Cosine Similarity between: 


Document 4 and Document 1:  [[0.49395987]]
Document 4 and Document 2:  [[0.60352796]]
Document 4 and Document 3:  [[0.3047918]]
