Name         Adeel Naeem
Roll         Bs-Ai (146)


In [1]:
import torch
random=torch.randint(low=0,high=9,size=(3,3)).type(torch.FloatTensor)
random1=torch.randint(low=0,high=5,size=(3,3)).type(torch.FloatTensor)

minimum=torch.min(random)

print(f" data:\n{random}")

print(f"minimum number is:{minimum}")

 data:
tensor([[6., 2., 8.],
        [5., 5., 2.],
        [4., 3., 0.]])
minimum number is:0.0


Explaination:

torch.randint(low=0, high=9, size=(3,3)): Generates a 3x3 tensor with random integers between 0 and 8.
.type(torch.FloatTensor): Converts the tensor's data type to a floating-point tensor (FloatTensor).

torch.min(random): Finds and returns the minimum value in the random tensor.

In [2]:
means=torch.mean(random)
print(f"mean of the date set :{means}")

mean of the date set :3.8888888359069824


Explaination:

torch.mean(random): Computes the mean (average) of all the values in the random tensor.


In [3]:
maximum=torch.max(random)
print(f"the max number is : {maximum}")

the max number is : 8.0


Explaination:

torch.max(random): Finds and returns the maximum value in the random tensor.

In [4]:
max_all=torch.argmax(random)
print(f"the over all maximum number is at index :{max_all}")

the over all maximum number is at index :2


EXlaination:

torch.argmax(random): Returns the index of the largest value in the random tensor when flattened.

In [5]:
min_all=torch.argmin(random)
print(f"the minimum number is at index:{min_all}")

the minimum number is at index:8


Explaination:

torch.argmin(random): Returns the index of the smallest value in the random tensor when flattened.

In [6]:
stack=torch.stack([random,random1],dim=0)
print(f"stacked matrices are:\n{stack}")

stacked matrices are:
tensor([[[6., 2., 8.],
         [5., 5., 2.],
         [4., 3., 0.]],

        [[4., 1., 1.],
         [4., 0., 1.],
         [2., 1., 2.]]])


Explaination

torch.stack([random, random1], dim=0): Stacks(concenate) random and random1 tensors along a new dimension (axis 0).


In [7]:
unsqueezed=torch.unsqueeze(random,dim=0)
print(f"unsqueezed tensor:\n{unsqueezed}")
squeezed=torch.squeeze(unsqueezed,dim=0)
print(f"squeezed tensor :\n{squeezed}")

unsqueezed tensor:
tensor([[[6., 2., 8.],
         [5., 5., 2.],
         [4., 3., 0.]]])
squeezed tensor :
tensor([[6., 2., 8.],
        [5., 5., 2.],
        [4., 3., 0.]])


Explaination:

torch.unsqueeze(random, dim=0): Adds an extra dimension to the random tensor at position 0.

torch.squeeze(unsqueezed, dim=0): Removes the extra dimension from the unsqueezed tensor at position 0.

In [11]:
random_view=random.view(-1)
print(f"view the reshape data:\n{random_view}")
random_reshape=random.view(9,1)
print(random_reshape)


view the reshape data:
tensor([6., 2., 8., 5., 5., 2., 4., 3., 0.])
tensor([[6.],
        [2.],
        [8.],
        [5.],
        [5.],
        [2.],
        [4.],
        [3.],
        [0.]])


Explaination:

random.view(-1): Reshapes the random tensor into a 1D tensor (flattening it).

random.view(9, 1): Reshapes the random tensor into a 9x1 matrix.

     ---------------------------------------  The End  -------------------------------------------